### ISSUE TITLE
not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by SExpert12** [janwithb/carla-gym-wrapper#6]
Hi, 
I run this file.

python3 carla_env_test.py

and I got this error:

logger.warn(f"{pre} is not within the observation space.")
Traceback (most recent call last):
  File "carla_env_test.py", line 9, in <module>
    next_obs, reward, done, done,info = env.step([1, 0])
  File "/home/ryzen/carla-gym-wrapper-main/gymagent/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 52, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)

When I trace it is actually 4 values but I don't know how to modify code.
How to resolve this?

**Comment by janwithb** [comment]
Hi @SExpert12 
Instead of:
`next_obs, reward, done, done,info = env.step([1, 0])`
could you try the following:
`next_obs, reward, done, info = env.step([1, 0])`

**Comment by SExpert12** [comment]
Sure.
Thanks for your reply.
